spring:
  application:
    name: sgp
  datasource:
    url: jdbc:mysql://localhost:3306/sgp14
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: true